### ISSUE TITLE
WebPack --watch command is giving exception

### ISSUE THREAD

**Issue by harisaru** [jaredly/treed#26]
Hi,

When i am trying to run the application as per the instructions, i am getting following error Kindly let me know where i am doing wrong:

Invalid configuration object. Webpack has been initialised using a configuration
 object that does not match the API schema.
 - configuration has an unknown property 'colors'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?,
entry, externals?, loader?, module?, name?, node?, output?, performance?, plugin
s?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, res
olveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configura
tion.
     Loaders should be updated to allow passing options via loader options in mo
dule.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these
 options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           colors: ...
         }
       })
     ]
 - configuration.output.path: The provided value "./" is not an absolute path!

Regards,
HariKrishna

**Comment by eyotang** [comment]
I have the same exception, then I comment the colors. It passed.
But a few minutes later, It throw another exception.

 # webpack --watch --config webpack.config.js

Webpack is watching the files…

/usr/local/lib/node_modules/webpack/lib/Chunk.js:49
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/usr/local/lib/node_modules/webpack/lib/Chunk.js:49:9)
    at /root/sourcecode/treed/node_modules/extract-text-webpack-plugin/index.js:116:13
    at Array.filter (native)
    at ExtractTextPlugin.<anonymous> (/root/sourcecode/treed/node_modules/extract-text-webpack-plugin/index.js:115:37)
    at Compilation.applyPlugins0 (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/usr/local/lib/node_modules/webpack/lib/Compilation.js:567:8)
    at applyPluginsParallel.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:514:17)
    at /usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/usr/local/lib/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Samdyddd** [comment]
how to solve this problem?

**Comment by hamidhaghdoost** [comment]
and I have same error...

**Comment by spacegangster** [comment]
Solved this in my fork https://github.com/spacegangster/treed
